[platformio]
src_dir = .

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Provisional board target.
; Change this once the exact ESP32-S3 development board is purchased.

[env:esp32-s3-fixed]
extends = env:esp32-s3-devkitc-1
build_flags = -DV0_FIXED_CONDITION
